import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Poppins } from "next/font/google";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  style: ["normal", "italic"],
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${poppins.className} h-full`}>
      <body className='h-full' suppressHydrationWarning={true}>
        <div className='bg-cover bg-gradient-to-r from-red-500 to-red-300 h-fit'>
          {children}
        </div>
      </body>
    </html>
  );
}